#!/bin/sh

command -v jshint >/dev/null 2>&1 || {
    echo >&2 "I require jshint but it's not installed.  Aborting."; exit 1; 
}

if [ "$#" -eq 0 ];
then
    echo "Usage:"
    echo "\t`basename $0` [directory]"
    echo "\n\tThis will check all the JS files in the directory with JSHint"
else
    FILES=$(find $1 -type f -name "*.js")
    for i in $FILES; do
        jshint $i
    done
fi

