#!/bin/sh

usage(){
    echo "Usage:\n\n\tremove-audio input output\n"
    echo "Example:\n\n\t remove-audio video_input.ogv video_no_audio.ogv\n"
}

# Check parameters, if not enough show usage
if [ $# -le 1 ]; then
    usage
    exit 1
fi

ffmpeg -i $1 -vcodec copy -an $2
